"""create bot_users, bot_providers, bot_missions

Revision ID: 86e6cd29a3eb
Revises: 
Create Date: 2026-08-01 11:09:31.673424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e6cd29a3eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_missions',
    sa.Column('mission_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('commune', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_index(op.f('ix_bot_missions_telegram_id'), 'bot_missions', ['telegram_id'], unique=False)
    op.create_table('bot_providers',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('communes', sa.JSON(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('bot_users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_users')
    op.drop_table('bot_providers')
    op.drop_index(op.f('ix_bot_missions_telegram_id'), table_name='bot_missions')
    op.drop_table('bot_missions')
    # ### end Alembic commands ###
