"""add provider reputation fields, mission money fields, quotes and transactions tables

Revision ID: be8b67fa1f0e
Revises: 86e6cd29a3eb
Create Date: 2026-08-01 13:56:24.430932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8b67fa1f0e'
down_revision: Union[str, Sequence[str], None] = '86e6cd29a3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('provider_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('delay_hours', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['bot_missions.mission_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_quotes_mission_id'), 'bot_quotes', ['mission_id'], unique=False)
    op.create_index(op.f('ix_bot_quotes_provider_telegram_id'), 'bot_quotes', ['provider_telegram_id'], unique=False)
    op.create_table('bot_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('tola_fee', sa.Float(), nullable=False),
    sa.Column('aggregator_fee', sa.Float(), nullable=False),
    sa.Column('net_provider', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mobile_money_ref', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['bot_missions.mission_id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['bot_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_transactions_mission_id'), 'bot_transactions', ['mission_id'], unique=False)
    op.add_column('bot_missions', sa.Column('provider_telegram_id', sa.BigInteger(), nullable=True))
    op.add_column('bot_missions', sa.Column('commission_amount', sa.Float(), nullable=False))
    op.add_column('bot_missions', sa.Column('tola_fee', sa.Float(), nullable=False))
    op.add_column('bot_missions', sa.Column('aggregator_fee', sa.Float(), nullable=False))
    op.add_column('bot_missions', sa.Column('total_client', sa.Float(), nullable=False))
    op.add_column('bot_missions', sa.Column('net_provider', sa.Float(), nullable=False))
    op.add_column('bot_missions', sa.Column('dispute_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_bot_missions_provider_telegram_id'), 'bot_missions', ['provider_telegram_id'], unique=False)
    op.add_column('bot_providers', sa.Column('module', sa.String(length=1), nullable=False))
    op.add_column('bot_providers', sa.Column('badge', sa.String(length=20), nullable=False))
    op.add_column('bot_providers', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('bot_providers', sa.Column('total_missions', sa.Integer(), nullable=False))
    op.add_column('bot_providers', sa.Column('success_rate', sa.Float(), nullable=False))
    op.add_column('bot_providers', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('bot_providers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('bot_providers', sa.Column('is_suspended', sa.Boolean(), nullable=False))
    op.add_column('bot_providers', sa.Column('consecutive_ignored', sa.Integer(), nullable=False))
    op.add_column('bot_providers', sa.Column('wallet_balance_usd', sa.Float(), nullable=False))
    op.add_column('bot_providers', sa.Column('wallet_balance_cdf', sa.Float(), nullable=False))
    op.add_column('bot_users', sa.Column('wallet_balance_usd', sa.Float(), nullable=False))
    op.add_column('bot_users', sa.Column('wallet_balance_cdf', sa.Float(), nullable=False))
    op.add_column('bot_users', sa.Column('total_missions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_users', 'total_missions')
    op.drop_column('bot_users', 'wallet_balance_cdf')
    op.drop_column('bot_users', 'wallet_balance_usd')
    op.drop_column('bot_providers', 'wallet_balance_cdf')
    op.drop_column('bot_providers', 'wallet_balance_usd')
    op.drop_column('bot_providers', 'consecutive_ignored')
    op.drop_column('bot_providers', 'is_suspended')
    op.drop_column('bot_providers', 'is_active')
    op.drop_column('bot_providers', 'is_verified')
    op.drop_column('bot_providers', 'success_rate')
    op.drop_column('bot_providers', 'total_missions')
    op.drop_column('bot_providers', 'rating')
    op.drop_column('bot_providers', 'badge')
    op.drop_column('bot_providers', 'module')
    op.drop_index(op.f('ix_bot_missions_provider_telegram_id'), table_name='bot_missions')
    op.drop_column('bot_missions', 'dispute_reason')
    op.drop_column('bot_missions', 'net_provider')
    op.drop_column('bot_missions', 'total_client')
    op.drop_column('bot_missions', 'aggregator_fee')
    op.drop_column('bot_missions', 'tola_fee')
    op.drop_column('bot_missions', 'commission_amount')
    op.drop_column('bot_missions', 'provider_telegram_id')
    op.drop_index(op.f('ix_bot_transactions_mission_id'), table_name='bot_transactions')
    op.drop_table('bot_transactions')
    op.drop_index(op.f('ix_bot_quotes_provider_telegram_id'), table_name='bot_quotes')
    op.drop_index(op.f('ix_bot_quotes_mission_id'), table_name='bot_quotes')
    op.drop_table('bot_quotes')
    # ### end Alembic commands ###
